#!/bin/bash

sockFile=~/.ssh/.agent.sock

function startAgent() {
  if [ ! -f $sockFile ]; then
    ssh-agent -s > $sockFile
  fi
  . $sockFile > /dev/null
}

if [ -d ~/.ssh ]; then
  startAgent

  if [ ! -S "$SSH_AUTH_SOCK" ]; then
    rm -f $sockFile
  fi

  startAgent
fi
