#!/bin/bash

al=~/.bash_aliases

if [ -f $al ] && [ ! -h $al ];then
  mv $al ${al}.backup;
fi

if [ ! -h $al ];then
  ln -s "`rPath .bash_aliases`" $al
fi

if [ ! -f ~/.bash_profile ];then
  touch ~/.bash_profile
fi

if [ -z "`grep -o 'bash_aliases' ~/.bash_profile`" ];then
modifiedHeaderTo '#' ~/.bash_profile
  cat >> ~/.bash_profile <<~

if [ -f $al ];then
  . $al > /dev/null;
fi
export PATH="$BIN_DIR:\$PATH";
~
fi
