#!/bin/bash

al=$HOME/.bash_aliases
rc=$HOME/.bashrc

if [ -f $al ] && [ ! -h $al ];then
  mv $al ${al}.backup;
fi

if [ ! -h $al ];then
  ln -s "`rPath .bash_aliases`" $al
fi

if [ ! -f "$rc" ];then
  cat > "$rc" <<~
#!/bin/bash
~
fi

if [ -z "`grep -o 'bash_aliases' "$rc"`" ];then
modifiedHeaderTo '#' "$rc"
  cat >> "$rc" <<~

if [ -f '$al' ];then
  . '$al' > /dev/null;
fi

if [ -f '`rPath start-agent`' ]; then
  . '`rPath start-agent`'
fi
export PATH="$BIN_DIR:\$PATH";

~
fi
