#!/bin/bash

al="$HOME/.bash_aliases"
configDir="$HOME/.config"
terminatorConfigDir="$configDir/terminator"
terminatorConfig="$terminatorConfigDir/config"
rc="$HOME/.bashrc"
ternProject="$HOME/.tern-project"

if [ -f "$al" ] && [ ! -h "$al" ];then
  mv "$al" "${al}.backup";
fi

if [ ! -h "$al" ];then
  ln -s "`rPath .bash_aliases`" "$al"
fi

if [ ! -h "$terminatorConfig" ];then
  rm -f "$terminatorConfig"
  mkdir -p "$terminatorConfigDir"
  ln -s "`rPath .terminator_config`" "$terminatorConfig"
fi

if [ ! -h "$ternProject" ];then
  ln -s "`rPath .tern-project`" "$ternProject"
fi

if [ ! -f "$rc" ];then
  cat > "$rc" <<~
#!/bin/bash
~
fi

if [ -z "`grep -o 'bash_aliases' "$rc"`" ];then
modifiedHeaderTo '#' "$rc"
  cat >> "$rc" <<~

if [ -f '$al' ];then
  . '$al' > /dev/null;
fi

if [ -f '`rPath start-agent`' ]; then
  . '`rPath start-agent`'
fi
# Remove this if you want to enable vim-bootstrap.
export BASH_BOOTSTRAP_NO_VIM="$BASH_BOOTSTRAP_NO_VIM"
export PATH="$BIN_DIR:\$PATH"

~
fi
