#!/bin/bash

if [ -f ~/.bash_aliases ] && [ ! -h ~/.bash_aliases ];then
  mv ~/.bash_aliases ~/.bash_aliases.backup;
  rm ~/.bash_aliases
  ln -s "`rPath .bash_aliases`" ~/.bash_aliases
fi

if [ -z "`grep -o 'bash_aliases' ~/.bashrc`" ];then
modifiedHeaderTo '#' ~/.bashrc
  cat >> ~/.bashrc <<~

if [ -f ~/.bash_aliases ];then
  . ~/.bash_aliases > /dev/null;
fi
~
fi
