#!/bin/bash

git config --global push.default simple
git config --global core.autocrlf input
git config --global core.editor vim
git config --global core.excludesfile '~/.bash-bootstrap/resources/.global_gitignore'
