#!/bin/bash
set -e

#setup plugins
if [ ! -d ~/.vim ];then
  git clone https://github.com/jsdevel/vim-bootstrap.git ~/.vim
fi

#Prevent cd from changing the directory
(cd ~/.vim;git pull origin master;git submodule update --init);

mkdir -p ~/.vim/bundle

#setup .vimrc
if [ -f ~/.vimrc ] && [ ! -f ~/.vimrc.backup ] && [ ! -h ~/.vimrc ];then
  cp ~/.vimrc ~/.vimrc.backup
  modifiedHeaderTo '"' ~/.vimrc.backup
  rm ~/.vimrc
fi

if [ -f ~/.vimrc ];then
  rm ~/.vimrc
fi

ln -s ~/.vim/.vimrc ~/.vimrc

vim +PluginInstall +qall
