#!/bin/bash

if [ -f ~/.vimrc ] && [ ! -f ~/.vimrc.backup ] && [ ! -h ~/.vimrc ];then
  cp ~/.vimrc ~/.vimrc.backup 
  modifiedHeaderTo '"' ~/.vimrc.backup
  rm ~/.vimrc
fi

rm ~/.vimrc

ln -s "`rPath .vimrc`" ~/.vimrc

mkdir -p ~/.vim/autoload ~/.vim/bundle 2>/dev/null

if [ ! -d ~/.vim/.git ];then
  git clone https://github.com/jsdevel/vim-bootstrap.git ~/.vim
fi

#Prevent cd from changing the directory
(cd ~/.vim;git pull origin master;git submodule update --init);

curl -Sso ~/.vim/autoload/pathogen.vim \
    https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
